"""empty message

Revision ID: f9a7d6bfd27c
Revises: 006ab3cd96f3
Create Date: 2024-08-19 20:13:48.396253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9a7d6bfd27c'
down_revision = '006ab3cd96f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.Text(), nullable=True))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('image')

    # ### end Alembic commands ###
